### ISSUE TITLE
upstream服务器被解析为IPv6地址

### ISSUE THREAD

**Issue by gfw-breaker** [gfw-breaker/ssr-accounts#1]
有时upstream服务器被解析为IPv6地址，如图所示，导致nginx服务短暂几秒中断。该如何设置操作系统只解析IPv4地址？
![default](https://user-images.githubusercontent.com/34854165/34904248-1db71ee4-f87d-11e7-9de3-d8f88e45c52c.png)

**Comment by Alvin9999** [comment]
把vultr vps的ipv6关掉试试

**Comment by gfw-breaker** [comment]
操作系统为CentOS 6, 修改/boot/grub/grub.conf, 添加内核参数 ipv6.disable=1, 重启即可
![default](https://user-images.githubusercontent.com/34854165/34942453-b16e75ea-fa32-11e7-9ecf-6c94f895af25.png)
