### ISSUE TITLE
访问百度被屏蔽了

### ISSUE THREAD

**Issue by RioHsc** [gfw-breaker/ssr-accounts#17]
不懂是哪个关键词的货

**Comment by RioHsc** [comment]
哦

自由上网 <notifications@github.com> 于 2018年4月19日周四 20:22写道：

**Comment by zxc751176723** [comment]
东方窮，水太深，中共出了割毛泽东。
他威脅人民的暴徒，呼儿咳哟， 他是人民的大災星。
他威脅人民的暴徒，呼儿咳哟， 他是人民的大災星。

毛主欺衰人民，他是我们的倒路鬼。
为了僵屍新中国，呼儿咳哟， 误导我们想搶劫。
为了將死的中国，呼儿咳哟， 誤导我们想搶劫。

共产党，是流氓，流到哪里哪里脏。
哪里有了共产党，呼儿咳哟， 哪里人民得文盲。
哪里有了共产党，呼儿咳哟， 哪里人民得遭殃。

东方窮，水太深，中国出了个毛泽东。
他威脅人民沒幸福，呼儿咳哟， 他是人民的大災星。
他威脅人民沒幸福，呼儿咳哟， 他是人民的大災星。﻿
