### ISSUE TITLE
上一些墙外网站时，证书是gfw-breaker.win，而非原本域名的证书

### ISSUE THREAD

**Issue by nothing12138** [gfw-breaker/ssr-accounts#21]
NET::ERR_CERT_COMMON_NAME_INVALID
Subject: gfw-breaker.win

Issuer: Let's Encrypt Authority X3

Expires on: 2018年12月10日

Current date: 2018年11月24日

**Comment by gfw-breaker** [comment]
是的，屏蔽了一些网站，重定向到 gfw-breaker.win 详情请见 https://github.com/gfw-breaker/ssr-accounts/wiki  
大部分网友可能就上上 Twitter、YouTube之类的，或者查资料看新闻，是不受影响的。
