### ISSUE TITLE
之前的是美国节点还更新吗？

### ISSUE THREAD

**Issue by Nan-2019** [gfw-breaker/ssr-accounts#28]
美国节点可以登陆我的Spotify，现在日本的登不了了！😢

**Comment by gfw-breaker** [comment]
@Nan-2019 日本的节点速度最快，美国节点延时比日本的大多了。登不了具体是什么问题？

**Comment by Nan-2019** [comment]
> @Nan-2019 日本的节点速度最快，美国节点延时比日本的大多了。登不了具体是什么问题？

我的Spotify账号是美区注册的，所以只有在美区服务器才能登陆。

**Comment by Nan-2019** [comment]
@gfw-breaker 我改了Spotify的地区，可以登录了，谢谢！
