### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Mabbs** [gfw-breaker/ssr-accounts#32]
混淆最好不要用tls1.2_ticket_auth
几乎是秒封，刚刚又挂了。。。
用http_simple反倒更好一些

**Comment by p19971018** [comment]
对呀，现在又不能访问了

**Comment by gfw-breaker** [comment]
好的， 但现在GFW又有重大升级了，即使换了混淆也很快就检测出来了

**Comment by Spr1nt0a0** [comment]
什么时候更新呀

**Comment by gfw-breaker** [comment]
@Spr1nt0a0 不知道，我试了不下10个，都不能用。

**Comment by DaLiangLee** [comment]
都挂了..

**Comment by yexiongkai** [comment]
ssr 的tls混淆缺陷在
https://github.com/shadowsocksrr/shadowsocksr-csharp/issues/199

**Comment by p19971018** [comment]
试了其他的ssr账号，发现还是这个最快，但现在不能用了，哎，，，

**Comment by Mabbs** [comment]
> 试了其他的ssr账号，发现还是这个最快，但现在不能用了，哎，，，

你可以去TG上收SSR，那个上面的SSR速度不错

**Comment by Alvin9999** [comment]
@p19971018 什么不能用？
