### ISSUE TITLE
现在哪家vps主机的提供商好用

### ISSUE THREAD

**Issue by VVVVictorJ** [gfw-breaker/ssr-accounts#33]
vultr ip好像都被封干净了 洛杉矶的都用不了

**Comment by Alvin9999** [comment]
避开热门区域，比如洛杉矶和日东东京。热门区域用的人多，ip被墙的数量也会很多。

**Comment by VVVVictorJ** [comment]
> 避开热门区域，比如洛杉矶和日东东京。热门区域用的人多，ip被墙的数量也会很多。

我试了美国其他地区的，和悉尼，伦敦的。达拉斯的能ssh上，别的都不行，延迟都很高，达拉斯也是。
悉尼延迟也很高，有没有别的厂商推荐的

**Comment by Alvin9999** [comment]
changeip

**Comment by VVVVictorJ** [comment]
> changeip

我换了好多了，实在没耐心了:( 
还是说本地ip也要换？

**Comment by Alvin9999** [comment]
changeip是一个vps商的名字哦

**Comment by Alvin9999** [comment]
需要提醒的是这家ip如果被墙，换ip要3美元1个。

**Comment by Alvin9999** [comment]
还是这个https://www.digitalocean.com/  ，这个跟vultr类似，换ip也是免费的，按小时计费

**Comment by VVVVictorJ** [comment]
> changeip
嗷嗷，这样的啊


> 需要提醒的是这家ip如果被墙，换ip要3美元1个。

直接删除，重开的话，原本的也是收费的吗

> 还是这个https://www.digitalocean.com/ ，这个跟vultr类似，换ip也是免费的，按小时计费

好的，蟹蟹

**Comment by Alvin9999** [comment]
changeip直接删除就相当于你白买了。

**Comment by VVVVictorJ** [comment]
> changeip直接删除就相当于你白买了。

那假如一开始就是被封的ip，不就相当于白给了。

**Comment by Alvin9999** [comment]
嗯 ，有风险

**Comment by gfw-breaker** [comment]
@VVVVictorJ Vultr 基本上不可用了。昨天试了下 https://panel.op-net.com/，欧洲有几个数据中心可用。但是这个平台的VPS流量是Inbound + Outbound 累加收费的，相当于实际能使用的流量只有它提供的一半。

**Comment by VVVVictorJ** [comment]
> @VVVVictorJ Vultr 基本上不可用了。昨天试了下 https://panel.op-net.com/ ，欧洲有几个数据中心可用。但是这个平台的VPS流量是Inbound + Outbound 累加收费的，相当于实际能使用的流量只有它提供的一半。

那还可以当备用方案用。

**Comment by 21want28k** [comment]
移动网络ping不同服务器了，不知道为啥。移动网络整体被断了吗？

**Comment by VVVVictorJ** [comment]
> 移动网络ping不同服务器了，不知道为啥。移动网络整体被断了吗？

延迟高吧，试了下可以的
