### ISSUE TITLE
禁书推荐很有意思，不开心的多看看，看看你就开心了

### ISSUE THREAD

**Issue by he11oChina** [gfw-breaker/ssr-accounts#34]
我看到了下面一段话——“中国人只有彻底觉醒，彻底摒弃共产邪恶主义、共产邪党，回归传统，回归神，中华民族才能复兴！一个背离神的民族怎么能够得到神的护佑？！无神论是共产邪灵毁灭人类的圈套！”
  看到了吗996的兄弟们，快回归财神爷的怀抱，不要工作了，天天上香拜佛，争取早日财富自由，实现中华民族的伟大复兴啊，哈哈哈哈哈哈哈
  本来Github一个技术交流平台被这样搞我也是真的服了，果然是有钱能使鬼推磨，一些人拿了钱什么都干

**Comment by Wesegm** [comment]
是啊，有些人拿了钱什么都能干。

**Comment by gfw-breaker** [comment]
@Wesegm 在你的价值观里，貌似人做事的唯一动力就只有钱财。 也不管事实究竟是如何，上来就自己脑补别人拿钱了，毫无客观理性的态度，这样只会使自己越来越封闭。

**Comment by Wesegm** [comment]
@gfw-breaker  在你的世界里，是不是除了特别明显的诋毁，就没有客观，没有plain facts，也不管是不是事实如此？你说的节目我都追了几集，我觉得我有一点发言权。就算你没收钱，那也离翻墙初衷open eyes Open Mind 差很远。都是屁股坐死的节目，你敢说你没有带节奏？收钱完全是合理的推测，带这种节奏，不是蠢就是坏，或者两者兼有。

**Comment by gfw-breaker** [comment]
@Wesegm  什么是明显的诋毁呀？请指明一二。

**Comment by Wesegm** [comment]
@gfw-breaker  No comment. 提示下看看你在哪发的言。
