### ISSUE TITLE
看来更新端口已经不行了

### ISSUE THREAD

**Issue by Superstroller** [gfw-breaker/ssr-accounts#42]

**Comment by gfw-breaker** [comment]
换IP了

**Comment by 008Linc** [comment]
IP和端口在哪看？

**Comment by gfw-breaker** [comment]
@008Linc   就在那个表格里呀

**Comment by 008Linc** [comment]
？？？初来报到，，，还搞不清楚在哪

**Comment by HeiLAAS** [comment]
换了也连不上了

**Comment by kbfx1234** [comment]
好像连不上了呀

**Comment by gfw-breaker** [comment]
@kbfx1234 马上要十一了，大批SS阵亡，暂时用下别的工具吧

**Comment by kbfx1234** [comment]
好的谢谢啦



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 翻墙教练 <notifications@github.com&gt;
发送时间: 2019年9月17日 10:17
收件人: gfw-breaker/ssr-accounts <ssr-accounts@noreply.github.com&gt;
抄送: kbfx1234 <893489808@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[gfw-breaker/ssr-accounts] 看来更新端口已经不行了 (#42)




@kbfx1234 马上要十一了，大批SS阵亡，暂时用下别的工具吧
